### ISSUE TITLE
"Ignoring debase" error

### ISSUE THREAD

**Issue by DerpTwerp** [stevenharman/git_tracker#22]
I have just recently started getting the following error when I try to use git commit with a git-tracker enabled repo:
```
Ignoring debase-0.2.2.beta11 because its extensions are not built.  Try: gem pristine debase --version 0.2.2.beta11
Ignoring debase-0.2.2.beta10 because its extensions are not built.  Try: gem pristine debase --version 0.2.2.beta10
Ignoring debase-0.2.1 because its extensions are not built.  Try: gem pristine debase --version 0.2.1
```

My Ruby version is: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

Running the suggested commands did not solve anything and I am unsure what else to do.

**Comment by stevenharman** [comment]
How did you install `git-tracker`? The gem has no run-time dependencies, so I'm not sure where `debase` is coming from.

**Comment by DerpTwerp** [comment]
Just reconfirmed (via brew uninstall & gem uninstall) that it was installed via brew. Reinstalled it via brew again and confirmed the same error.

**Comment by stevenharman** [comment]
Is the `debase` gem installed on your system? I assume so, but I have no idea why `git-tracker` is tripping up over it b/c `git-tracker` has no runtime dependencies other than Ruby's standard lib. Do other Ruby programs (e.g., `irb` or something like `ruby -e "puts [:Hello, :world].join(' ')"`) also hit the `debase` problem?

**Comment by DerpTwerp** [comment]
Running the command you requested, produced no error. 
I did `gem uninstall debase` (not sure why it was installed to begin with) and reran git tracker and that caused the error to go away.
I reinstalled debase and the error returned.
I am cool with uninstalling debase until I figure out what I had that needed it.
Sorry I didn't think to try uninstalling that first.

**Comment by stevenharman** [comment]
It's odd that Debase is causing such trouble, but I'm honestly not familiar enough with it to know where to start debugging this. But... there is an open issue on debase that might be helpful to track: https://github.com/denofevil/debase/issues/54

**Comment by stevenharman** [comment]
Closing as stale.
